### ISSUE TITLE
Consignment

### ISSUE THREAD

**Issue by Michael-Opremic** [opremic-solutions-gmbh/mrosmarthub#25]
The connector should be enabled to handle consignments.
A consignment supplier can open a new consignment project with a consignment taker. Base information for every consignment is a list of materials. Before the consignment material is actually published under the label of the taker a minimum price for each part has to be negotiated. Communication in these negotiations is supported with a separate chat for each consignment project. Additional information like documentation with certificates can be requested by the taker and uploaded by the supplier.
Material that has been sold via the connector or elsewhere will be shown in tabular form and removed from connector consignment listing.

To do:

- [x] Add possibility to open consignment projects
- [x] Add upload possibility (UI and web service) for a consignment project
- [x] Add process to negotiate minimum prices for consignment materials
- [x] Link material with a negotiated expected price on connector
- [x] Track sold consignment material

**Comment by opremicSebastian** [comment]
Consignment module is productive with v0.23 and used by first customers
